### ISSUE TITLE
config.g lost when removing duetsd?

### ISSUE THREAD

**Issue by beikeland** [chrishamm/DuetSoftwareFramework#74]
Not quite sure what happened but something got out of whack with the dsf dependencies, and I tried removing the packages and reinstalling them, and probably because config.g is part of the duetsd package it was deleted and replaced with the default and pretty much empty config.g, this might not be immediately obvious to the end user.

Does it make sense having a default config.g in this case, when all it does is set the machine name, presumably because dwc has a different default name?

**Comment by chrishamm** [comment]
config.g is part of the duetsd conffiles file. That means dpkg knows it is a special file that is ignored when updating, but it's fairly possible that it is automatically deleted when the package is removed again.

Having at least an empty file is mandatory because DCS sets the datetime and hostname only when it is run. Besides, dpkg may remove this file again from already installed instances on updating if I remove it again. So I am not willing to remove the preset from the duetsd package.
